# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from .types.agent_think_agent_management_request_on_listening_action import (
    AgentThinkAgentManagementRequestOnListeningAction,
)
from .types.agent_think_agent_management_request_on_speaking_action import (
    AgentThinkAgentManagementRequestOnSpeakingAction,
)
from .types.agent_think_agent_management_request_on_thinking_action import (
    AgentThinkAgentManagementRequestOnThinkingAction,
)
from .types.agent_think_agent_management_response import AgentThinkAgentManagementResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def agent_think(
        self,
        appid: str,
        agent_id: str,
        *,
        text: str,
        on_listening_action: typing.Optional[AgentThinkAgentManagementRequestOnListeningAction] = OMIT,
        on_thinking_action: typing.Optional[AgentThinkAgentManagementRequestOnThinkingAction] = OMIT,
        on_speaking_action: typing.Optional[AgentThinkAgentManagementRequestOnSpeakingAction] = OMIT,
        interruptable: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentThinkAgentManagementResponse]:
        """
        Send a custom text instruction to the specified conversational AI agent instance.

        The instruction is injected into the current conversation pipeline as user input, and the agent processes and responds to it following the standard user input logic.

        Use this endpoint for the following scenarios:
        - **Implicit instruction injection**: Inject hidden context or directives into the conversation.
        - **Client-side event triggering**: Notify the agent of client-side events, such as a user clicking a button.
        - **Voice and text collaboration**: Combine text instructions with voice input for richer interaction.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        text : str
            The custom instruction text to inject into the current conversation pipeline. The system processes this as user input.

        on_listening_action : typing.Optional[AgentThinkAgentManagementRequestOnListeningAction]
            The action to take when the agent is in a listening state:
            - `inject`: Inject the custom text instruction into the current turn without interrupting it.
            - `ignore`: Ignore the request.

        on_thinking_action : typing.Optional[AgentThinkAgentManagementRequestOnThinkingAction]
            The action to take when the agent is in a thinking state:
            - `interrupt`: Interrupt the current state and start a new conversation turn.
            - `ignore`: Ignore the request.

        on_speaking_action : typing.Optional[AgentThinkAgentManagementRequestOnSpeakingAction]
            The action to take when the agent is in a speaking state:
            - `interrupt`: Interrupt the current state and start a new conversation turn.
            - `ignore`: Ignore the request.

        interruptable : typing.Optional[bool]
            Whether user speech can interrupt the injected instruction:
            - `true`: User speech can interrupt the instruction.
            - `false`: User speech cannot interrupt the instruction.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata in key-value pair format. Use this field to pass additional business information such as identifiers or model references.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentThinkAgentManagementResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/agents/{jsonable_encoder(agent_id)}/think",
            method="POST",
            json={
                "text": text,
                "on_listening_action": on_listening_action,
                "on_thinking_action": on_thinking_action,
                "on_speaking_action": on_speaking_action,
                "interruptable": interruptable,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentThinkAgentManagementResponse,
                    construct_type(
                        type_=AgentThinkAgentManagementResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def agent_think(
        self,
        appid: str,
        agent_id: str,
        *,
        text: str,
        on_listening_action: typing.Optional[AgentThinkAgentManagementRequestOnListeningAction] = OMIT,
        on_thinking_action: typing.Optional[AgentThinkAgentManagementRequestOnThinkingAction] = OMIT,
        on_speaking_action: typing.Optional[AgentThinkAgentManagementRequestOnSpeakingAction] = OMIT,
        interruptable: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentThinkAgentManagementResponse]:
        """
        Send a custom text instruction to the specified conversational AI agent instance.

        The instruction is injected into the current conversation pipeline as user input, and the agent processes and responds to it following the standard user input logic.

        Use this endpoint for the following scenarios:
        - **Implicit instruction injection**: Inject hidden context or directives into the conversation.
        - **Client-side event triggering**: Notify the agent of client-side events, such as a user clicking a button.
        - **Voice and text collaboration**: Combine text instructions with voice input for richer interaction.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        text : str
            The custom instruction text to inject into the current conversation pipeline. The system processes this as user input.

        on_listening_action : typing.Optional[AgentThinkAgentManagementRequestOnListeningAction]
            The action to take when the agent is in a listening state:
            - `inject`: Inject the custom text instruction into the current turn without interrupting it.
            - `ignore`: Ignore the request.

        on_thinking_action : typing.Optional[AgentThinkAgentManagementRequestOnThinkingAction]
            The action to take when the agent is in a thinking state:
            - `interrupt`: Interrupt the current state and start a new conversation turn.
            - `ignore`: Ignore the request.

        on_speaking_action : typing.Optional[AgentThinkAgentManagementRequestOnSpeakingAction]
            The action to take when the agent is in a speaking state:
            - `interrupt`: Interrupt the current state and start a new conversation turn.
            - `ignore`: Ignore the request.

        interruptable : typing.Optional[bool]
            Whether user speech can interrupt the injected instruction:
            - `true`: User speech can interrupt the instruction.
            - `false`: User speech cannot interrupt the instruction.

        metadata : typing.Optional[typing.Dict[str, str]]
            Custom metadata in key-value pair format. Use this field to pass additional business information such as identifiers or model references.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentThinkAgentManagementResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/agents/{jsonable_encoder(agent_id)}/think",
            method="POST",
            json={
                "text": text,
                "on_listening_action": on_listening_action,
                "on_thinking_action": on_thinking_action,
                "on_speaking_action": on_speaking_action,
                "interruptable": interruptable,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentThinkAgentManagementResponse,
                    construct_type(
                        type_=AgentThinkAgentManagementResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
