# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

"""Agora Conversational AI Python SDK."""

import typing
from importlib import import_module

from . import agentkit as _agentkit

if typing.TYPE_CHECKING:
    from . import agents, agentkit, core, phone_numbers, telephony
    from .core.domain import Area, Pool, create_pool
    from .pool_client import Agora, AsyncAgora, AgentClient, AsyncAgentClient
    from .version import __version__
    from .agentkit import (
        Agent,
        AgentSession,
        AgentSessionOptions,
        CNAgent,
        GlobalAgent,
        RegionalAgent,
        generate_rtc_token,
        GenerateTokenOptions,
        # Global (non-CN) vendor classes — re-exported from agentkit for static typing so
        # `from agora_agent import DeepgramSTT` autocompletes. Runtime resolution and
        # `__all__` membership come from the `__getattr__` fallback + the `__all__` union
        # below, so these need no `_dynamic_imports` / `_ROOT_ALL` entries.
        # CN vendors are intentionally not here — import them from `agora_agent.cn`.
        AkoolAvatar,
        AmazonBedrock,
        AmazonSTT,
        AmazonTTS,
        AnamAvatar,
        Anthropic,
        AresSTT,
        AssemblyAISTT,
        AzureOpenAI,
        CartesiaTTS,
        CustomLLM,
        DeepgramSTT,
        DeepgramTTS,
        Dify,
        ElevenLabsTTS,
        FishAudioTTS,
        Gemini,
        GeminiLive,
        GenericAvatar,
        GenericTTS,
        GoogleSTT,
        GoogleTTS,
        Groq,
        HeyGenAvatar,
        HumeAITTS,
        LiveAvatarAvatar,
        MicrosoftSTT,
        MicrosoftTTS,
        MiniMaxTTS,
        MurfTTS,
        OpenAI,
        OpenAIRealtime,
        OpenAISTT,
        OpenAITTS,
        RimeTTS,
        SarvamSTT,
        SarvamTTS,
        SpeechmaticsSTT,
        VertexAI,
        VertexAILLM,
        XaiGrok,
        XaiSTT,
        XaiTTS,
    )
    from .agentkit.agent_session import AsyncAgentSession

_dynamic_imports: typing.Dict[str, str] = {
    "Agora": ".pool_client",
    "Agent": ".agentkit",
    "AgentClient": ".pool_client",
    "AgentSession": ".agentkit",
    "AgentSessionOptions": ".agentkit",
    "Area": ".core.domain",
    "AsyncAgentSession": ".agentkit.agent_session",
    "AsyncAgora": ".pool_client",
    "AsyncAgentClient": ".pool_client",
    "GenerateTokenOptions": ".agentkit",
    "__version__": ".version",
    "agentkit": ".agentkit",
    "agents": ".agents",
    "core": ".core",
    "create_pool": ".core.domain",
    "generate_rtc_token": ".agentkit",
    "phone_numbers": ".phone_numbers",
    "telephony": ".telephony",
}

_ROOT_ALL = (
    "Agora",
    "Agent",
    "AgentClient",
    "AgentSession",
    "AgentSessionOptions",
    "Area",
    "AsyncAgentSession",
    "AsyncAgora",
    "AsyncAgentClient",
    "GenerateTokenOptions",
    "Pool",
    "__version__",
    "agentkit",
    "agents",
    "core",
    "create_pool",
    "generate_rtc_token",
    "phone_numbers",
    "telephony",
)

__all__ = sorted({*_ROOT_ALL, *_agentkit.__all__})


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is not None:
        try:
            module = import_module(module_name, __package__)
            if module_name == f".{attr_name}":
                return module
            return getattr(module, attr_name)
        except ImportError as e:
            raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
        except AttributeError as e:
            raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e

    if attr_name in _agentkit.__all__:
        return getattr(_agentkit, attr_name)

    raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")


def __dir__() -> typing.List[str]:
    return list(__all__)
