# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_history_agents_response_contents_item_role import GetHistoryAgentsResponseContentsItemRole


class GetHistoryAgentsResponseContentsItem(UncheckedBaseModel):
    role: typing.Optional[GetHistoryAgentsResponseContentsItemRole] = pydantic.Field(default=None)
    """
    The message sender:
    - `user`: User
    - `assistant`: AI agent
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Message content.
    """

    speech_start_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The start timestamp of the speech segment in milliseconds, relative to the beginning of the current session. Returned only when `llm.vendor='custom'`.
    """

    speech_end_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    The end timestamp of the speech segment in milliseconds, relative to the beginning of the current session. Returned only when `llm.vendor='custom'`.
    """

    speech_algorithmic_delay: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total delay in milliseconds introduced by audio processing algorithms, including noise reduction, background voice suppression, and voiceprint locking, after audio is captured from the user's microphone. Use this value to align timestamps with cloud recording audio. Returned only when `llm.vendor='custom'`, `contents[].role='user'`, and actual voice input is present.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
