# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_interruption_disabled_config_strategy import (
    StartAgentsRequestPropertiesInterruptionDisabledConfigStrategy,
)


class StartAgentsRequestPropertiesInterruptionDisabledConfig(UncheckedBaseModel):
    """
    Configuration for agent behavior when interruption is disabled. Applicable only when `interruption.enable` is `false`.
    """

    strategy: typing.Optional[StartAgentsRequestPropertiesInterruptionDisabledConfigStrategy] = pydantic.Field(
        default=None
    )
    """
    The processing strategy when interruption is disabled:
    - `append`: User speech does not interrupt the agent. The agent processes the user's input after the current interaction ends.
    - `ignore`: The agent ignores user speech. If the agent receives user speech while speaking or thinking, it discards the input without storing it in context.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
