# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_mllm_turn_detection_server_vad_config_end_of_speech_sensitivity import (
    StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfigEndOfSpeechSensitivity,
)
from .start_agents_request_properties_mllm_turn_detection_server_vad_config_start_of_speech_sensitivity import (
    StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfigStartOfSpeechSensitivity,
)


class StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfig(UncheckedBaseModel):
    """
    Configuration for vendor-side VAD-based turn detection. Applicable when `mode` is `server_vad`. Parameters are passed through to the vendor.
    """

    prefix_padding_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of audio in milliseconds to include before the detected speech start.
    """

    silence_duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of silence in milliseconds required to determine end of speech.
    """

    threshold: typing.Optional[float] = pydantic.Field(default=None)
    """
    VAD sensitivity threshold. Applicable to OpenAI Realtime API only.
    """

    idle_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Idle timeout in milliseconds. Applicable to OpenAI Realtime API only.
    """

    start_of_speech_sensitivity: typing.Optional[
        StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfigStartOfSpeechSensitivity
    ] = pydantic.Field(default=None)
    """
    Sensitivity for start of speech detection. Applicable to Gemini Live only.
    """

    end_of_speech_sensitivity: typing.Optional[
        StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfigEndOfSpeechSensitivity
    ] = pydantic.Field(default=None)
    """
    Sensitivity for end of speech detection. Applicable to Gemini Live only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
