# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentsRequestPropertiesParametersAudioScenario = typing.Union[
    typing.Literal["default", "chorus", "aiserver"], typing.Any
]
