# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_mllm_turn_detection_agora_vad_config import (
    StartAgentsRequestPropertiesMllmTurnDetectionAgoraVadConfig,
)
from .start_agents_request_properties_mllm_turn_detection_mode import StartAgentsRequestPropertiesMllmTurnDetectionMode
from .start_agents_request_properties_mllm_turn_detection_semantic_vad_config import (
    StartAgentsRequestPropertiesMllmTurnDetectionSemanticVadConfig,
)
from .start_agents_request_properties_mllm_turn_detection_server_vad_config import (
    StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfig,
)


class StartAgentsRequestPropertiesMllmTurnDetection(UncheckedBaseModel):
    """
    Turn detection configuration for the MLLM module. When defined, the top-level `turn_detection` object has no effect.
    """

    mode: typing.Optional[StartAgentsRequestPropertiesMllmTurnDetectionMode] = pydantic.Field(default=None)
    """
    Turn detection mode for MLLM:
    - `agora_vad`: Agora VAD-based detection.
    - `server_vad`: Vendor-side VAD-based detection. Supported by OpenAI Realtime API and Gemini Live.
    - `semantic_vad`: Semantic-based detection. Supported by OpenAI Realtime API only.
    """

    agora_vad_config: typing.Optional[StartAgentsRequestPropertiesMllmTurnDetectionAgoraVadConfig] = pydantic.Field(
        default=None
    )
    """
    Configuration for Agora VAD-based turn detection. Applicable when `mode` is `agora_vad`.
    """

    server_vad_config: typing.Optional[StartAgentsRequestPropertiesMllmTurnDetectionServerVadConfig] = pydantic.Field(
        default=None
    )
    """
    Configuration for vendor-side VAD-based turn detection. Applicable when `mode` is `server_vad`. Parameters are passed through to the vendor.
    """

    semantic_vad_config: typing.Optional[StartAgentsRequestPropertiesMllmTurnDetectionSemanticVadConfig] = (
        pydantic.Field(default=None)
    )
    """
    Configuration for semantic-based turn detection. Applicable when `mode` is `semantic_vad`. Supported by OpenAI Realtime API only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
