# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentsRequestPropertiesAvatarVendor = typing.Union[
    typing.Literal["akool", "liveavatar", "anam", "generic", "heygen", "sensetime"], typing.Any
]
