# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentsRequestPropertiesInterruptionDisabledConfigStrategy = typing.Union[
    typing.Literal["append", "ignore"], typing.Any
]
