# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agents_request_properties_interruption_disabled_config import (
    StartAgentsRequestPropertiesInterruptionDisabledConfig,
)
from .start_agents_request_properties_interruption_keywords_config import (
    StartAgentsRequestPropertiesInterruptionKeywordsConfig,
)
from .start_agents_request_properties_interruption_mode import StartAgentsRequestPropertiesInterruptionMode


class StartAgentsRequestPropertiesInterruption(UncheckedBaseModel):
    """
    Interruption control configuration. Provides unified management of the agent's behavior when interrupted by the user.
    """

    enable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable agent interruption:
    - `true`: Enable interruption.
    - `false`: Disable interruption. When disabled, the agent cannot be interrupted mid-response.
    """

    mode: typing.Optional[StartAgentsRequestPropertiesInterruptionMode] = pydantic.Field(default=None)
    """
    The interruption trigger mode:
    - `start_of_speech`: Trigger interruption when the user starts speaking.
    - `keywords`: Trigger interruption when the user speaks a specified keyword. Configure the trigger keywords in `keywords_config`.
    """

    keywords_config: typing.Optional[StartAgentsRequestPropertiesInterruptionKeywordsConfig] = pydantic.Field(
        default=None
    )
    """
    Configuration for keyword-based interruption triggering. Applicable only when `mode` is `keywords`.
    """

    disabled_config: typing.Optional[StartAgentsRequestPropertiesInterruptionDisabledConfig] = pydantic.Field(
        default=None
    )
    """
    Configuration for agent behavior when interruption is disabled. Applicable only when `interruption.enable` is `false`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
