# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class StartAgentsRequestPropertiesMllmTurnDetectionAgoraVadConfig(UncheckedBaseModel):
    """
    Configuration for Agora VAD-based turn detection. Applicable when `mode` is `agora_vad`.
    """

    interrupt_duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum duration of speech in milliseconds required to trigger an interruption.
    """

    prefix_padding_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of audio in milliseconds to include before the detected speech start.
    """

    silence_duration_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Duration of silence in milliseconds required to determine end of speech.
    """

    threshold: typing.Optional[float] = pydantic.Field(default=None)
    """
    VAD sensitivity threshold. A higher value reduces false positives.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
