# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentsRequestPropertiesTurnDetectionConfigEndOfSpeechMode = typing.Union[
    typing.Literal["vad", "semantic", "manual"], typing.Any
]
