# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class AmazonAsrParams(UncheckedBaseModel):
    """
    Amazon Transcribe ASR configuration parameters.
    """

    region: str = pydantic.Field()
    """
    AWS region
    """

    access_key_id: str = pydantic.Field()
    """
    AWS access key ID
    """

    secret_access_key: str = pydantic.Field()
    """
    AWS secret access key
    """

    language_code: str = pydantic.Field()
    """
    Language code for speech recognition
    """

    media_sample_rate_hz: typing.Optional[int] = pydantic.Field(default=None)
    """
    Sample rate in Hertz for the audio input
    """

    media_encoding: typing.Optional[str] = pydantic.Field(default=None)
    """
    Encoding format of the audio input
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
