# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .amazon_tts_params_engine import AmazonTtsParamsEngine


class AmazonTtsParams(UncheckedBaseModel):
    """
    Amazon Polly TTS configuration parameters.
    """

    aws_access_key_id: str = pydantic.Field()
    """
    AWS access key ID
    """

    aws_secret_access_key: str = pydantic.Field()
    """
    AWS secret key
    """

    region_name: str = pydantic.Field()
    """
    AWS region (e.g., "us-east-1")
    """

    voice: str = pydantic.Field()
    """
    Amazon Polly voice ID
    """

    engine: AmazonTtsParamsEngine = pydantic.Field()
    """
    Amazon Polly engine type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
