# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .ares_asr_params import AresAsrParams
from .asr_language import AsrLanguage


class AresAsr(UncheckedBaseModel):
    """
    Adaptive Recognition Engine for Speech ASR configuration.
    """

    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[AresAsrParams] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
