# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .amazon_asr_params import AmazonAsrParams
from .ares_asr_params import AresAsrParams
from .asr_language import AsrLanguage
from .assembly_ai_asr_params import AssemblyAiAsrParams
from .deepgram_asr_params import DeepgramAsrParams
from .google_asr_params import GoogleAsrParams
from .microsoft_asr_params import MicrosoftAsrParams
from .open_ai_asr_params import OpenAiAsrParams
from .sarvam_asr_params import SarvamAsrParams
from .speechmatics_asr_params import SpeechmaticsAsrParams


class Asr_Tencent(UncheckedBaseModel):
    vendor: typing.Literal["tencent"] = "tencent"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Dict[str, typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Fengming(UncheckedBaseModel):
    vendor: typing.Literal["fengming"] = "fengming"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Xfyun(UncheckedBaseModel):
    vendor: typing.Literal["xfyun"] = "xfyun"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_XfyunBigmodel(UncheckedBaseModel):
    vendor: typing.Literal["xfyun_bigmodel"] = "xfyun_bigmodel"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_XfyunDialect(UncheckedBaseModel):
    vendor: typing.Literal["xfyun_dialect"] = "xfyun_dialect"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Ares(UncheckedBaseModel):
    vendor: typing.Literal["ares"] = "ares"
    language: typing.Optional[AsrLanguage] = None
    params: typing.Optional[AresAsrParams] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Microsoft(UncheckedBaseModel):
    vendor: typing.Literal["microsoft"] = "microsoft"
    language: typing.Optional[AsrLanguage] = None
    params: MicrosoftAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Deepgram(UncheckedBaseModel):
    vendor: typing.Literal["deepgram"] = "deepgram"
    language: typing.Optional[AsrLanguage] = None
    params: DeepgramAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Openai(UncheckedBaseModel):
    vendor: typing.Literal["openai"] = "openai"
    language: typing.Optional[AsrLanguage] = None
    params: OpenAiAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Google(UncheckedBaseModel):
    vendor: typing.Literal["google"] = "google"
    language: typing.Optional[AsrLanguage] = None
    params: GoogleAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Amazon(UncheckedBaseModel):
    vendor: typing.Literal["amazon"] = "amazon"
    language: typing.Optional[AsrLanguage] = None
    params: AmazonAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Assemblyai(UncheckedBaseModel):
    vendor: typing.Literal["assemblyai"] = "assemblyai"
    language: typing.Optional[AsrLanguage] = None
    params: AssemblyAiAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Speechmatics(UncheckedBaseModel):
    vendor: typing.Literal["speechmatics"] = "speechmatics"
    language: typing.Optional[AsrLanguage] = None
    params: SpeechmaticsAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Asr_Sarvam(UncheckedBaseModel):
    vendor: typing.Literal["sarvam"] = "sarvam"
    language: typing.Optional[AsrLanguage] = None
    params: SarvamAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Asr = typing_extensions.Annotated[
    typing.Union[
        Asr_Ares,
        Asr_Microsoft,
        Asr_Deepgram,
        Asr_Openai,
        Asr_Google,
        Asr_Amazon,
        Asr_Assemblyai,
        Asr_Speechmatics,
        Asr_Sarvam,
        Asr_Tencent,
        Asr_Fengming,
        Asr_Xfyun,
        Asr_XfyunBigmodel,
        Asr_XfyunDialect,
    ],
    UnionMetadata(discriminant="vendor"),
]
