# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class AssemblyAiAsrParams(UncheckedBaseModel):
    """
    AssemblyAI ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    AssemblyAI API key
    """

    language: str = pydantic.Field()
    """
    Language code for speech recognition
    """

    uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket URL for AssemblyAI's streaming API
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
