# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class BytedanceDuplexTtsParams(UncheckedBaseModel):
    """
    Bytedance duplex streaming TTS configuration parameters.
    """

    app_id: str = pydantic.Field()
    """
    Bytedance application ID.
    """

    token: str = pydantic.Field()
    """
    Bytedance API token.
    """

    speaker: str = pydantic.Field()
    """
    Duplex TTS speaker identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
