# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class BytedanceTtsParams(UncheckedBaseModel):
    """
    Bytedance Volcano Engine TTS configuration parameters.
    """

    token: str = pydantic.Field()
    """
    Bytedance API token.
    """

    app_id: str = pydantic.Field()
    """
    Bytedance application ID.
    """

    cluster: str = pydantic.Field()
    """
    Bytedance cluster name.
    """

    voice_type: str = pydantic.Field()
    """
    Bytedance voice type.
    """

    speed_ratio: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed ratio.
    """

    volume_ratio: typing.Optional[float] = pydantic.Field(default=None)
    """
    Volume ratio.
    """

    pitch_ratio: typing.Optional[float] = pydantic.Field(default=None)
    """
    Pitch ratio.
    """

    emotion: typing.Optional[str] = pydantic.Field(default=None)
    """
    Emotion preset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
