# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .cartesia_tts_output_format import CartesiaTtsOutputFormat
from .cartesia_tts_voice import CartesiaTtsVoice


class CartesiaTtsParams(UncheckedBaseModel):
    """
    Cartesia TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Cartesia API key
    """

    model_id: str = pydantic.Field()
    """
    Model ID (for example, sonic-2)
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket URL for the Cartesia streaming API
    """

    voice: CartesiaTtsVoice
    output_format: typing.Optional[CartesiaTtsOutputFormat] = None
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target language for speech synthesis
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
