# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class CosyvoiceTtsParams(UncheckedBaseModel):
    """
    CosyVoice TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    CosyVoice API key.
    """

    model: str = pydantic.Field()
    """
    CosyVoice model identifier.
    """

    sample_rate: int = pydantic.Field()
    """
    Audio sample rate in Hz.
    """

    voice: str = pydantic.Field()
    """
    CosyVoice speaker voice.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
