# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DeepgramAsrParams(UncheckedBaseModel):
    """
    Deepgram ASR configuration parameters.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket URL for Deepgram's streaming API
    """

    key: str = pydantic.Field()
    """
    Deepgram API key
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Speech recognition model
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech recognition
    """

    keyterm: typing.Optional[str] = pydantic.Field(default=None)
    """
    Boost specialized terms and brands
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
