# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DeepgramTtsParams(UncheckedBaseModel):
    """
    Deepgram TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Deepgram API key
    """

    model: str = pydantic.Field()
    """
    Deepgram TTS model (for example, "aura-2-thalia-en")
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deepgram WebSocket endpoint override
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sampling rate in Hz
    """

    params: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional Deepgram TTS parameters
    """

    skip_patterns: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    Controls whether the TTS module skips bracketed content when reading LLM response text.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
