# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class FishAudioTtsParams(UncheckedBaseModel):
    """
    Fish Audio TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Fish Audio API key
    """

    reference_id: str = pydantic.Field()
    """
    Fish Audio reference ID
    """

    backend: str = pydantic.Field()
    """
    Backend model version to use
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
