# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class GenericHttpTtsParams(UncheckedBaseModel):
    """
    Generic TTS configuration parameters.
    """

    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key for the generic TTS service.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    TTS model name.
    """

    voice: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice name.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech rate.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Output audio sample rate in Hz.
    """

    response_format: typing.Optional[typing.Literal["pcm"]] = pydantic.Field(default=None)
    """
    Output audio format. ConvoAI currently supports `pcm` only.
    """

    instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional voice style control instruction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
