# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .generic_http_tts_params import GenericHttpTtsParams


class GenericHttpTts(UncheckedBaseModel):
    """
    Generic OpenAI-compatible Text-to-Speech configuration.
    """

    url: str = pydantic.Field()
    """
    Callback address of the generic TTS service.
    """

    headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Custom headers to include in requests to the generic TTS service.
    """

    params: GenericHttpTtsParams
    skip_patterns: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    Controls whether the TTS module skips bracketed content when reading LLM response text.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
