# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class GoogleAsrParams(UncheckedBaseModel):
    """
    Google ASR configuration parameters.
    """

    project_id: str = pydantic.Field()
    """
    Google Cloud project ID
    """

    location: str = pydantic.Field()
    """
    Google Cloud region for the speech service
    """

    adc_credentials_string: str = pydantic.Field()
    """
    Google Cloud service account credentials JSON string
    """

    language: str = pydantic.Field()
    """
    Language code for speech recognition
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Recognition model to use
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
