# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class GradiumTtsParams(UncheckedBaseModel):
    """
    Gradium TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Gradium API key.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket endpoint for streaming TTS output (for example, "wss://api.gradium.ai/api/speech/tts").
    """

    model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Gradium TTS model name (for example, "default").
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Gradium voice identifier.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz (for example, 16000).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
