# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .llm_params import LlmParams
from .llm_style import LlmStyle


class Llm(UncheckedBaseModel):
    """
    Large language model (LLM) configuration.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The LLM callback address.
    """

    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The LLM verification API key.
    """

    access_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    AWS access key ID. Used by Amazon Bedrock when api_key is not provided.
    """

    secret_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    AWS secret access key. Used by Amazon Bedrock when api_key is not provided.
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    AWS region. Used by Amazon Bedrock.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Top-level model identifier. Used by Amazon Bedrock.
    """

    system_messages: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    A set of predefined information used as input to the LLM.
    """

    params: typing.Optional[LlmParams] = None
    max_history: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of conversation history messages cached in the custom LLM.
    """

    input_modalities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    LLM input modalities.
    """

    output_modalities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    LLM output modalities.
    """

    greeting_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent greeting.
    """

    failure_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Prompt for agent activation failure.
    """

    vendor: typing.Optional[str] = pydantic.Field(default=None)
    """
    LLM provider identifier.
    """

    style: typing.Optional[LlmStyle] = pydantic.Field(default=None)
    """
    The request style for chat completion.
    """

    ignore_empty: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to handle empty Gemini responses.
    """

    greeting_configs: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Agent greeting broadcast configuration.
    """

    template_variables: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Template parameter configuration.
    """

    mcp_servers: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    MCP server configuration.
    """

    headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Custom headers to include in requests to the LLM.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
