# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .llm_greeting_configs_uninterruptible_asr_policy import LlmGreetingConfigsUninterruptibleAsrPolicy


class LlmGreetingConfigs(UncheckedBaseModel):
    """
    Agent greeting broadcast configuration.
    """

    audio_download_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout in milliseconds for downloading greeting audio.
    """

    audio_pcm_sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Sample rate in Hz for PCM greeting audio.
    """

    uninterruptible_asr_policy: typing.Optional[LlmGreetingConfigsUninterruptibleAsrPolicy] = pydantic.Field(
        default=None
    )
    """
    Policy for handling ASR text during uninterruptible greeting playback.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
