# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MicrosoftAsrParams(UncheckedBaseModel):
    """
    Microsoft Azure ASR configuration parameters.
    """

    key: str = pydantic.Field()
    """
    Microsoft Azure API key
    """

    region: str = pydantic.Field()
    """
    Azure region
    """

    language: str = pydantic.Field()
    """
    Language code for speech recognition
    """

    phrase_list: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Words or phrases to improve recognition accuracy
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
