# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .minimax_tts_params_audio_setting import MinimaxTtsParamsAudioSetting
from .minimax_tts_params_pronunciation_dict import MinimaxTtsParamsPronunciationDict
from .minimax_tts_params_timber_weights_item import MinimaxTtsParamsTimberWeightsItem
from .minimax_tts_params_voice_setting import MinimaxTtsParamsVoiceSetting


class MinimaxTtsParams(UncheckedBaseModel):
    """
    MiniMax TTS configuration parameters.
    """

    key: str = pydantic.Field()
    """
    MiniMax API key
    """

    group_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    MiniMax group identifier
    """

    model: str = pydantic.Field()
    """
    BYOK TTS model. Managed MiniMax preset models are selected through the top-level preset field instead.
    """

    voice_setting: MinimaxTtsParamsVoiceSetting
    audio_setting: typing.Optional[MinimaxTtsParamsAudioSetting] = pydantic.Field(default=None)
    """
    Audio output settings.
    """

    pronunciation_dict: typing.Optional[MinimaxTtsParamsPronunciationDict] = pydantic.Field(default=None)
    """
    Custom pronunciation dictionary settings.
    """

    timber_weights: typing.Optional[typing.List[MinimaxTtsParamsTimberWeightsItem]] = pydantic.Field(default=None)
    """
    Weighted voice blending configuration.
    """

    language_boost: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language boost mode.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket endpoint (e.g., wss://api-uw.minimax.io/ws/v1/t2a_v2)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
