# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MinimaxTtsParamsVoiceSetting(UncheckedBaseModel):
    voice_id: str = pydantic.Field()
    """
    Voice style identifier (e.g., English_captivating_female1)
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed multiplier.
    """

    vol: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice volume multiplier.
    """

    pitch: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice pitch adjustment.
    """

    emotion: typing.Optional[str] = pydantic.Field(default=None)
    """
    Emotion preset.
    """

    latex_read: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to read LaTeX expressions.
    """

    english_normalization: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to normalize English text before synthesis.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
