# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class MistralTtsParams(UncheckedBaseModel):
    """
    Mistral TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Mistral API key.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mistral TTS model name (for example, "voxtral-mini-tts-2603").
    """

    voice: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mistral voice identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
