# This file was auto-generated by Fern from our API Definition.

import typing

MllmTurnDetectionSemanticVadConfigEagerness = typing.Union[typing.Literal["auto", "low", "medium", "high"], typing.Any]
