# This file was auto-generated by Fern from our API Definition.

import typing

MllmTurnDetectionServerVadConfigEndOfSpeechSensitivity = typing.Union[
    typing.Literal["END_SENSITIVITY_HIGH", "END_SENSITIVITY_LOW"], typing.Any
]
