# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .mllm_params import MllmParams
from .mllm_turn_detection import MllmTurnDetection
from .mllm_vendor import MllmVendor


class Mllm(UncheckedBaseModel):
    """
    Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing.
    """

    enable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable Multimodal Large Language Model.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The MLLM WebSocket URL for real-time communication.
    """

    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The API key used for MLLM authentication.
    """

    adc_credentials_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base64-encoded Google Cloud Application Default Credentials. Used by Vertex AI.
    """

    project_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Google Cloud project ID. Used by Vertex AI.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Google Cloud location or region. Used by Vertex AI.
    """

    messages: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Array of conversation items used for short-term memory management.
    """

    params: typing.Optional[MllmParams] = None
    input_modalities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    MLLM input modalities.
    """

    output_modalities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    MLLM output modalities.
    """

    greeting_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent greeting message.
    """

    failure_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent failure message.
    """

    vendor: typing.Optional[MllmVendor] = pydantic.Field(default=None)
    """
    MLLM provider.
    """

    turn_detection: typing.Optional[MllmTurnDetection] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
