# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .mllm_turn_detection_agora_vad_config import MllmTurnDetectionAgoraVadConfig
from .mllm_turn_detection_mode import MllmTurnDetectionMode
from .mllm_turn_detection_semantic_vad_config import MllmTurnDetectionSemanticVadConfig
from .mllm_turn_detection_server_vad_config import MllmTurnDetectionServerVadConfig


class MllmTurnDetection(UncheckedBaseModel):
    """
    Turn detection configuration for the MLLM module.
    """

    mode: typing.Optional[MllmTurnDetectionMode] = pydantic.Field(default=None)
    """
    Turn detection mode for MLLM.
    """

    agora_vad_config: typing.Optional[MllmTurnDetectionAgoraVadConfig] = None
    server_vad_config: typing.Optional[MllmTurnDetectionServerVadConfig] = None
    semantic_vad_config: typing.Optional[MllmTurnDetectionSemanticVadConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
