# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .mllm_http_options import MllmHttpOptions
from .mllm_input_audio_transcription import MllmInputAudioTranscription


class MllmParams(UncheckedBaseModel):
    """
    Additional MLLM configuration parameters.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    The MLLM model identifier.
    """

    voice: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice identifier for audio output.
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    System instructions that define the agent behavior or tone.
    """

    input_audio_transcription: typing.Optional[MllmInputAudioTranscription] = None
    affective_dialog: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable Gemini affective dialog.
    """

    proactive_audio: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether Gemini may choose not to respond when no reply is needed.
    """

    transcribe_agent: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to transcribe the agent speech in real time.
    """

    transcribe_user: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to transcribe the user speech in real time.
    """

    http_options: typing.Optional[MllmHttpOptions] = None
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for xAI Grok speech recognition and synthesis.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
