# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .mllm_turn_detection_server_vad_config_end_of_speech_sensitivity import (
    MllmTurnDetectionServerVadConfigEndOfSpeechSensitivity,
)
from .mllm_turn_detection_server_vad_config_start_of_speech_sensitivity import (
    MllmTurnDetectionServerVadConfigStartOfSpeechSensitivity,
)


class MllmTurnDetectionServerVadConfig(UncheckedBaseModel):
    prefix_padding_ms: typing.Optional[int] = None
    silence_duration_ms: typing.Optional[int] = None
    threshold: typing.Optional[float] = None
    idle_timeout_ms: typing.Optional[int] = None
    start_of_speech_sensitivity: typing.Optional[MllmTurnDetectionServerVadConfigStartOfSpeechSensitivity] = None
    end_of_speech_sensitivity: typing.Optional[MllmTurnDetectionServerVadConfigEndOfSpeechSensitivity] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
