# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class MurfTtsParams(UncheckedBaseModel):
    """
    Murf TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Murf API key
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket endpoint for streaming TTS output
    """

    voice_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="voiceId")] = pydantic.Field(
        default=None
    )
    """
    Voice ID (e.g., Matthew)
    """

    locale: typing.Optional[str] = pydantic.Field(default=None)
    """
    Locale for the selected voice
    """

    rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech rate adjustment
    """

    pitch: typing.Optional[float] = pydantic.Field(default=None)
    """
    Pitch adjustment
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    TTS model to use
    """

    sample_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
