# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class OpenAiInputAudioTranscription(UncheckedBaseModel):
    """
    OpenAI audio transcription configuration.
    """

    model: str = pydantic.Field()
    """
    OpenAI ASR model to use for transcription
    """

    prompt: str = pydantic.Field()
    """
    Prompt that guides the transcription process
    """

    language: str = pydantic.Field()
    """
    Language code to use for transcription
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
