# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .open_ai_input_audio_transcription import OpenAiInputAudioTranscription


class OpenAiAsrParams(UncheckedBaseModel):
    """
    OpenAI ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    OpenAI API key
    """

    input_audio_transcription: OpenAiInputAudioTranscription

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
