# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class RimeTtsParams(UncheckedBaseModel):
    """
    Rime TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    Rime API key
    """

    speaker: str = pydantic.Field()
    """
    Rime speaker ID
    """

    model_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="modelId")] = pydantic.Field(
        default=None
    )
    """
    Rime TTS model ID
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket URL for the Rime streaming API
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
