# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .sarvam_tts_params_target_language_code import SarvamTtsParamsTargetLanguageCode


class SarvamTtsParams(UncheckedBaseModel):
    """
    Sarvam TTS configuration parameters.
    """

    api_subscription_key: str = pydantic.Field()
    """
    Sarvam API subscription key
    """

    speaker: str = pydantic.Field()
    """
    Voice ID (e.g., anushka, abhilash, karun, hitesh, manisha, vidya, arya)
    """

    target_language_code: SarvamTtsParamsTargetLanguageCode = pydantic.Field()
    """
    Target language code (e.g., en-IN)
    """

    pitch: typing.Optional[float] = pydantic.Field(default=None)
    """
    Pitch adjustment for the voice
    """

    pace: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed of speech
    """

    loudness: typing.Optional[float] = pydantic.Field(default=None)
    """
    Volume level of the speech
    """

    sample_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
