# This file was auto-generated by Fern from our API Definition.

import typing

SarvamTtsParamsTargetLanguageCode = typing.Union[
    typing.Literal["en-IN", "hi-IN", "bn-IN", "ta-IN", "te-IN", "kn-IN", "ml-IN", "mr-IN", "gu-IN", "pa-IN", "or-IN"],
    typing.Any,
]
