# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .sensetime_avatar_params_scene_list_item_digital_role_position import (
    SensetimeAvatarParamsSceneListItemDigitalRolePosition,
)


class SensetimeAvatarParamsSceneListItemDigitalRole(UncheckedBaseModel):
    face_feature_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    SenseTime face feature identifier.
    """

    position: typing.Optional[SensetimeAvatarParamsSceneListItemDigitalRolePosition] = None
    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Avatar model package URL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
