# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .sensetime_avatar_params_scene_list_item import SensetimeAvatarParamsSceneListItem


class SensetimeAvatarParams(UncheckedBaseModel):
    """
    SenseTime Avatar configuration parameters.
    """

    agora_token: str = pydantic.Field()
    """
    Agora token used by the avatar service.
    """

    agora_uid: str = pydantic.Field()
    """
    Numeric Agora UID string used by the avatar service.
    """

    app_id: typing_extensions.Annotated[str, FieldMetadata(alias="appId")] = pydantic.Field()
    """
    SenseTime application ID.
    """

    app_key: str = pydantic.Field()
    """
    SenseTime application key.
    """

    scene_list: typing_extensions.Annotated[
        typing.List[SensetimeAvatarParamsSceneListItem], FieldMetadata(alias="sceneList")
    ] = pydantic.Field()
    """
    SenseTime scene configuration list.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
