# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SpatiusAvatarParams(UncheckedBaseModel):
    """
    Spatius Avatar configuration parameters.
    """

    spatius_api_key: str = pydantic.Field()
    """
    Spatius API key.
    """

    spatius_app_id: str = pydantic.Field()
    """
    Spatius application ID.
    """

    spatius_avatar_id: str = pydantic.Field()
    """
    Spatius avatar ID.
    """

    agora_uid: str = pydantic.Field()
    """
    Agora UID used by the avatar service.
    """

    agora_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    RTC token generated for `agora_uid` in the target channel.
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    Spatius service region, for example `cn-beijing`.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz. Recommended to match the TTS sample rate.
    """

    session_expire_minutes: typing.Optional[int] = pydantic.Field(default=None)
    """
    Spatius session validity duration in minutes. Defaults to 30.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
