# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class StepfunTtsParams(UncheckedBaseModel):
    """
    StepFun TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    StepFun API key.
    """

    model: str = pydantic.Field()
    """
    StepFun model identifier.
    """

    voice_id: str = pydantic.Field()
    """
    StepFun voice identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
