# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TencentAsrParams(UncheckedBaseModel):
    """
    Tencent ASR configuration parameters.
    """

    key: str = pydantic.Field()
    """
    Tencent ASR secret key.
    """

    app_id: str = pydantic.Field()
    """
    Tencent Cloud application ID.
    """

    secret: str = pydantic.Field()
    """
    Tencent ASR secret.
    """

    engine_model_type: str = pydantic.Field()
    """
    Tencent ASR engine model type.
    """

    voice_id: str = pydantic.Field()
    """
    Tencent ASR voice session identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
