# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .asr_language import AsrLanguage
from .tencent_asr_params import TencentAsrParams


class TencentAsr(UncheckedBaseModel):
    """
    Tencent ASR configuration.
    """

    language: typing.Optional[AsrLanguage] = None
    params: TencentAsrParams

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
