# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TencentTtsParams(UncheckedBaseModel):
    """
    Tencent TTS configuration parameters.
    """

    app_id: str = pydantic.Field()
    """
    Tencent Cloud application ID.
    """

    secret_id: str = pydantic.Field()
    """
    Tencent Cloud secret ID.
    """

    secret_key: str = pydantic.Field()
    """
    Tencent Cloud secret key.
    """

    voice_type: int = pydantic.Field()
    """
    Tencent voice type identifier.
    """

    volume: typing.Optional[float] = pydantic.Field(default=None)
    """
    Volume setting.
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed setting.
    """

    emotion_category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Emotion category.
    """

    emotion_intensity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Emotion intensity.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
