# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class XAiAsrParams(UncheckedBaseModel):
    """
    xAI ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    xAI API key
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    WebSocket endpoint URL for the xAI streaming STT API. Defaults to `wss://api.x.ai/v1/stt`.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Language code for speech recognition.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
