# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class XAiTtsParams(UncheckedBaseModel):
    """
    xAI TTS configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    xAI API key.
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    xAI voice identifier.
    """

    language: str = pydantic.Field()
    """
    BCP-47 language code for speech synthesis.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Audio sample rate in Hz.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
