# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class XfyunAsrParams(UncheckedBaseModel):
    """
    iFlytek ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    iFlytek API key.
    """

    app_id: str = pydantic.Field()
    """
    iFlytek application ID.
    """

    api_secret: str = pydantic.Field()
    """
    iFlytek API secret.
    """

    language: str = pydantic.Field()
    """
    iFlytek language code.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
