# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class XfyunBigmodelAsrParams(UncheckedBaseModel):
    """
    iFlytek large-model ASR configuration parameters.
    """

    api_key: str = pydantic.Field()
    """
    iFlytek large-model API key.
    """

    app_id: str = pydantic.Field()
    """
    iFlytek large-model application ID.
    """

    api_secret: str = pydantic.Field()
    """
    iFlytek large-model API secret.
    """

    language_name: str = pydantic.Field()
    """
    iFlytek language family name.
    """

    language: str = pydantic.Field()
    """
    iFlytek language mode.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
