# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class XfyunDialectAsrParams(UncheckedBaseModel):
    """
    iFlytek dialect ASR configuration parameters.
    """

    app_id: str = pydantic.Field()
    """
    iFlytek dialect application ID.
    """

    access_key_id: str = pydantic.Field()
    """
    iFlytek access key ID.
    """

    access_key_secret: str = pydantic.Field()
    """
    iFlytek access key secret.
    """

    language: str = pydantic.Field()
    """
    Dialect recognition language code.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
