# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AgentThinkAgentManagementResponse(UncheckedBaseModel):
    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier of the agent instance.
    """

    channel: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the RTC channel where the agent is located.
    """

    start_ts: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timestamp indicating when the agent was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
